In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

import utils as ut

organism = 'others'

train_paths = [f'data/sp_data/train_set_partition_0_{organism}.json',
               f'data/sp_data/train_set_partition_1_{organism}.json']
val_paths = [f'data/sp_data/test_set_partition_0_{organism}.json',
             f'data/sp_data/test_set_partition_1_{organism}.json']
test_paths = [f'data/sp_data/train_set_partition_2_{organism}.json',
              f'data/sp_data/test_set_partition_2_{organism}.json']

train = pd.concat(pd.read_json(path) for path in ut.abspaths(train_paths))
val = pd.concat(pd.read_json(path) for path in ut.abspaths(val_paths))
test = pd.concat(pd.read_json(path) for path in ut.abspaths(test_paths))

keys = train['kingdom'].unique()
t = train['kingdom'].value_counts(sort=False).tolist()
# print(t.iloc[0])

plt.bar(keys, t, align='center')
xlocs, xlabs = plt.xticks()
for i, v in enumerate(t):
    plt.text(xlocs[i] - 0.1, v + 100, str(v))
plt.show()
# plt.savefig(fname=str(Path(params)))

In [ ]:
import torch

CKPT_PATH = './checkpoints/transformer_epoch=3_kaggle_v2.ckpt'

checkpoint = torch.load(CKPT_PATH)
print(checkpoint.keys())
print(checkpoint['state_dict'])

In [ ]:
import pandas as pd
import json

train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
val_paths = [f'data/sp_data/test_set_partition_0.json', f'data/sp_data/test_set_partition_1.json']
test_paths = [f'data/sp_data/train_set_partition_2.json', f'data/sp_data/test_set_partition_2.json']

train_data = []
val_data = []
test_data = []

for path in train_paths:
    with open(path, 'r') as f:
        data = json.load(f)
        train_data.extend(data)

train_data = pd.DataFrame(train_data)
train_data

In [ ]:
t = {
    "c": 4,
    "b": 2,
    "a": 3,
}

c = dict(a=1, b=2, c=3)

tt = dict(sorted(t.items(), key=lambda kv: c[kv[0]]))

In [ ]:
list(tt.keys())

In [1]:
len("MAPTLFQKLFSKRTGLGAPGRDARDPDCGFSWPLPEFDPSQIRLIVYQDCERRGRNVLFDSSVKRRNEDI")

70

In [7]:
import tokenizer.tokenizer_utils as tut
import torch
tokenizer = tut.load_tokenizer('cnn', 'smiles')
encoded = tokenizer.batch_encode_plus(["N[C@@H](CCSC)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCSC)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC1=CC=C(O)C=C1)C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)N[C@@H](CC1=CNC=N1)C(=O)N[C@@H](CC1=CNC=N1)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H](CCCNC(N)=N)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CCSC)C(=O)NCC(=O)N[C@@H](C)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](C)C(=O)N[C@@H](CS)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(N)=O)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CCC(N)=O)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCSC)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CCSC)C(=O)N[C@@H](CCCNC(N)=N)C(=O)NCC(=O)NCC(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC1=CC=C(O)C=C1)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(C))C(=O)O"])
print(torch.tensor(encoded['input_ids'][0]))

tensor([ 1, 13, 16, 11, 19, 12, 20, 38,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12,
        20, 33,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12, 20, 38,  6, 11, 21, 14,
         6, 13, 16, 11, 19, 12, 20, 33,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12,
        20, 25,  9, 18,  9, 11,  5, 14,  6, 11,  9, 27,  6, 11, 21, 14,  6, 13,
        16, 11, 19, 12, 20, 25,  9, 18,  9, 18,  9, 27,  6, 11, 21, 14,  6, 13,
        16, 11, 19, 12, 20, 25,  9, 36,  9, 29,  6, 11, 21, 14,  6, 13, 16, 11,
        19, 12, 20, 25,  9, 36,  9, 29,  6, 11, 21, 14,  6, 29, 16, 11, 19, 12,
        20, 35,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12, 20, 31,  6, 11, 21, 14,
         6, 28, 21, 14,  6, 13, 16, 11, 19, 12, 20, 18,  5, 11,  6, 11,  6, 11,
        21, 14,  6, 13, 16, 11, 19, 12, 20, 18,  5, 11,  6, 11,  6, 11, 21, 14,
         6, 29, 16, 11, 19, 12, 20, 35,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12,
        20, 34,  5, 13, 22, 13,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12, 20, 18,
         5, 11,  6, 11,  6, 11, 21, 14, 

In [ ]:
import params

a = list(params.SP_LABELS.keys()).insert(0, 'metrics')
b = list(params.SP_LABELS.keys())
b.insert(0, 'metrics')
print(a)

In [ ]:
import torch

p = torch.tensor([[1, 2, 3],
                  [1, 2, 5],
                  [4, 1, 1],
                  [2, 3, 2],
                  [2, 4, 2]], dtype=torch.float)
t = torch.tensor([2, 1, 0, 1, 2])
t2 = torch.tensor([2, 2, 0, 1, 2])

from sklearn.metrics import f1_score, classification_report
import numpy as np

from torchmetrics import F1Score

f1 = F1Score(task='multiclass', num_classes=3, average=None)

print(f1(p, t2))
print(f1_score(torch.argmax(p, dim=1).tolist(), t2.tolist(), average=None, zero_division=np.nan))
print(classification_report(torch.argmax(p, dim=1).tolist(), t2.tolist()))



In [ ]:

import torch

cm = torch.tensor([
    [1, 2, 3],
    [2, 4, 5],
    [3, 1, 2],
])

tp = torch.diag(cm)
fp = torch.sum(cm, dim=0) - tp
fn = torch.sum(cm, dim=1) - tp
tn = torch.sum(cm) - (tp + fn + fp)

denom = (tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)
torch.sqrt(denom)
# math.sqrt(denom)

# print((tp * tn + fp * fn) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)))

In [ ]:
n = torch.tensor([1, 2])
d = torch.tensor([2, 0])

z = torch.tensor(2)
if z == 0:
    print('true')

for i, j in zip(n, d):
    if j == 0:
        print(0)
    else:
        print((i / j).item())

In [8]:
from data.sp_dataset import SPDataset
from data.data_utils import SPBatchRandomSampler
import utils as ut
from torch.utils.data import DataLoader

train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
train_set = SPDataset(json_paths=ut.abspaths(train_paths), data_type='aa')
# torch.manual_seed(0)
sampler = SPBatchRandomSampler(train_set, batch_size=2, current_epoch=0, shuffle=True)
train_dataloader = DataLoader(train_set, batch_sampler=sampler)
for idx, batch in enumerate(train_dataloader):
    pass
    # print(idx, batch)

In [5]:
import torch

train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
train_set = SPDataset(json_paths=ut.abspaths(train_paths), data_type='aa')
print(range(3))
subset = torch.utils.data.Subset(train_set, range(3))
print(len(subset))

In [5]:
a = ((1, 2, 3), 4, 5)
b = ((4, 2, 3), 5, 7)
c = ((4, 6, 2), 4, 1)
batch = [a, b, c]
x, y, z = map(list, zip(*batch))
print(x, y, z)

In [21]:
from dgl.nn.pytorch import GraphConv
import dgl
import torch

num_nodes = 10

a = [0, 1, 2, 3, 4, 3]
b = [1, 0, 3, 2, 3, 4]
a1 = torch.zeros((num_nodes, num_nodes))
for i, j in zip(a, b):
    a1[i, j] = 1
g1 = dgl.graph((a, b), num_nodes=num_nodes)
g1 = dgl.add_self_loop(g1)
g1.ndata['h'] = a1

c = [0, 1, 2, 3, 6, 3]
d = [1, 0, 3, 2, 3, 6]
a2 = torch.zeros((num_nodes, num_nodes))
for i, j in zip(c, d):
    a2[i, j] = 1
g2 = dgl.graph((c, d), num_nodes=num_nodes)
g2 = dgl.add_self_loop(g2)
g2.ndata['h'] = a2

batch = dgl.batch([g1, g2])
# feats = torch.concat([a1, a2])

conv = GraphConv(in_feats=num_nodes, out_feats=2, allow_zero_in_degree=True)
ret = conv(batch, batch.ndata['h'])
# ret = conv(g2, a2)
print(torch.reshape(ret, (-1, num_nodes, 2)).shape)

In [5]:
from dgl.data import MiniGCDataset
import matplotlib.pyplot as plt
import networkx as nx

# A dataset with 80 samples, each graph is
# of size [10, 20]
dataset = MiniGCDataset(80, 10, 20)
graph, label = dataset[0]
fig, ax = plt.subplots()
nx.draw(graph.to_networkx(), ax=ax)
ax.set_title('Class: {:d}'.format(label))
plt.show()

In [13]:
import torch

t1 = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [1, 2, 3],
        [0, 0, 0]
    ]
])

t2 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [1,2,3]
])

split_ids = torch.tensor([2, 1])

d_model = 3

from itertools import islice

def split_batch(batch, split_ids, max_len):
    tmp = iter(batch)
    res = [list(islice(tmp, 0, ele)) for ele in split_ids]
    print(res)
    ret = []
    if max_len == "longest":
        max_len = torch.max(split_ids)
        # print(max_len)
    # if not isinstance(max_len, int):
    #     raise ValueError('Use `int` or "longest"')
    for ele in res:
        print(ele)
        if len(ele) > max_len:
            ret.append(torch.stack(ele[:max_len]))
        else:
            while len(ele) < max_len:
                pad = torch.zeros(d_model)
                ele.append(pad)
            ret.append(torch.stack(ele))
    return torch.stack(ret)
print(split_batch(t2, split_ids, "longest"))

[[tensor([1, 2, 3]), tensor([4, 5, 6])], [tensor([1, 2, 3])]]
[tensor([1, 2, 3]), tensor([4, 5, 6])]
[tensor([1, 2, 3])]
tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [0., 0., 0.]]])


In [1]:
import torch

t = torch.tensor([
    [1., 1., 1.],
    [1., 0., 0.]
])

t = t.masked_fill(t == 0, float('-inf'))
print(t)
t = t.masked_fill(t == 1, float(0.0))
print(t)

tensor([[1., 1., 1.],
        [1., -inf, -inf]])
tensor([[0., 0., 0.],
        [0., -inf, -inf]])


In [11]:
t = torch.zeros((8, 4))
t[:, -1] = float('-inf')
print(t)

tensor([[0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf]])


In [14]:
import torch
t1 = torch.tensor([0,0,0])
t2 = [
    torch.tensor([1,0,0]),
    torch.tensor([0,1,0]),
]
print(torch.stack([t1, *t2]))

tensor([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]])


In [15]:
t = [1,2,3]
t[len(t)]

IndexError: list index out of range

In [49]:
import pandas as pd
import utils as ut
import params
import numpy as np

df = pd.read_csv(ut.abspath(f'out/metrics/ap_score.csv'))
df_total = pd.read_csv(ut.abspath(f'out/metrics/ap_score_TOTAL.csv'))

models = df_total['model_type'].unique()
num_models = len(models)

ranking_table = np.zeros((len(params.ORGANISMS), num_models, num_models))
ranking_table_total = np.zeros((num_models, num_models))

# for TOTAL
for k, l in params.SP_LABELS.items():
    ranks = np.array(df_total[k].rank(method='min', ascending=False), dtype=int)
    for i, rank in enumerate(ranks):
        ranking_table_total[i][rank-1] += 1

for k1, o in params.ORGANISMS.items():
    for k2, l in params.SP_LABELS.items():
        if df[df['organism'] == k1][k2].sum() != 0.0:
            ranks = np.array(df[df['organism'] == k1][k2].rank(method='min', ascending=False), dtype=int)
            for i, rank in enumerate(ranks):
                ranking_table[o][i][rank-1] += 1
            
print(ranking_table)
print(ranking_table_total[15])
# df[df['organism'] == "EUKARYA"]
# for k, org in params.ORGANISMS.items():

CNN_default, smiles, Using Organism: True
[3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [1]:
from Bio import SeqIO
import data.data_utils as dut
from visualization import _statistics_on_total, _statistics_on_train_val_test
import json

records = SeqIO.parse(dut.SIGNALP6_PATH, 'fasta')
statistics_on_organisms, statistics_on_labels, statistics_on_labels_organism = _statistics_on_total(records)

# extract train/val/test set
train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
val_paths = [f'data/sp_data/test_set_partition_0.json', f'data/sp_data/test_set_partition_1.json']
test_paths = [f'data/sp_data/train_set_partition_2.json', f'data/sp_data/test_set_partition_2.json']

train_records, val_records, test_records = [], [], []
for train_path, val_path, test_path in zip(train_paths, val_paths, test_paths):
    with open(train_path, 'r') as f:
        train_records.extend(json.load(f))
    with open(val_path, 'r') as f:
        val_records.extend(json.load(f))
    with open(test_path, 'r') as f:
        test_records.extend(json.load(f))

statistics_on_train_organisms, statistics_on_train_labels, statistics_on_train_labels_organism = _statistics_on_train_val_test(
    train_records)
statistics_on_val_organisms, statistics_on_val_labels, statistics_on_val_labels_organism = _statistics_on_train_val_test(
    val_records)
statistics_on_test_organisms, statistics_on_test_labels, statistics_on_test_labels_organism = _statistics_on_train_val_test(
    test_records)

In [3]:
statistics_on_train_labels_organism

{'EUKARYA': {'NO_SP': 8603, 'SP': 1230},
 'POSITIVE': {'NO_SP': 97,
  'SP': 80,
  'LIPO': 379,
  'TAT': 29,
  'PILIN': 2,
  'TATLIPO': 1},
 'NEGATIVE': {'NO_SP': 396,
  'SP': 181,
  'LIPO': 606,
  'TAT': 188,
  'PILIN': 45,
  'TATLIPO': 13},
 'ARCHAEA': {'NO_SP': 52,
  'SP': 24,
  'LIPO': 7,
  'TAT': 9,
  'PILIN': 9,
  'TATLIPO': 5}}

In [12]:
import params
import pandas as pd
import utils as ut
orgs = []
lbs = [[], [], [], [], [], []]

for org in params.ORGANISMS.keys():
    orgs.append(org)
    for l, i in params.SP_LABELS.items():
        if l in statistics_on_test_labels_organism[org].keys():
            lbs[i].append(statistics_on_test_labels_organism[org][l])
        else:
            lbs[i].append(0)
        
dt = {
    "orgs": orgs,
    "NO_SP": lbs[0],
    "SP": lbs[1],
    "LIPO": lbs[2],
    "TAT": lbs[3],
    "PILIN": lbs[4],
    "TATLIPO": lbs[5]
}
df = pd.DataFrame(dt)
df.to_csv(ut.abspath(f'out/metrics/statistics_on_test_lbs_orgs.csv'), index=False, na_rep=0)

In [ ]:
import pandas as pd
df = pd.DataFrame(statistics_on_labels).transpose()
df.to_csv(ut.abspath(f'out/metrics/statistics_on_labels.csv.csv'))

In [2]:
import numpy as np
from sklearn.metrics import average_precision_score
# y_true = np.array([0, 0, 1, 1])
# y_scores = np.array([0.1, 0.4, 0.35, 0.8])
# average_precision_score(y_true, y_scores)
y_true = np.array([0, 0, 1, 1, 2, 2])
y_scores = np.array([
    [0.7, 0.2, 0.1],
    [0.4, 0.3, 0.3],
    [0.1, 0.8, 0.1],
    [0.2, 0.3, 0.5],
    [0.4, 0.4, 0.2],
    [0.1, 0.2, 0.7],
])

print(y_true.shape, y_scores.shape)
average_precision_score(y_true, y_scores)

(6,) (6, 3)


0.7777777777777777

In [10]:
import utils as ut
import pandas as pd

model = "cnn-aa-default-0_epochs=100"

file_org_loc = ut.abspath(f'out/metrics/{model}_ap_score_ORG.csv')
file_total_loc = ut.abspath(f'out/metrics/{model}_ap_score_TOTAL.csv')

ap_org = pd.read_csv(file_org_loc)
ap_total = pd.read_csv(file_total_loc)

ap_org[ap_org["index"] == 0]['model'].values[0]
# ap_total

'CNN, AA Seq, Organism: No'

In [17]:
from transformers import GPT2TokenizerFast
import data.data_utils as dut
from Bio import SeqIO
import json
import torch

tokenizer_path = ut.abspath(f'tokenizer/tokenizer_smiles.json')
tokenizer = GPT2TokenizerFast(tokenizer_file=tokenizer_path)
if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({'pad_token': '[PAD]'})

records = SeqIO.parse(dut.SIGNALP6_PATH, 'fasta')
max_len = [0, 0]
min_len = [1000, 10000]
# for record in records:
#     seq = str(record.seq)[:len(record.seq) // 2]
#     if len(seq) > max_len[0]:
#         max_len[0] = len(seq)
#     if len(seq) < min_len[0]:
#         min_len[0] = len(seq)
# print(max_len[0], min_len[0])

train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
val_paths = [f'data/sp_data/test_set_partition_0.json', f'data/sp_data/test_set_partition_1.json']
test_paths = [f'data/sp_data/train_set_partition_2.json', f'data/sp_data/test_set_partition_2.json']

train_records, val_records, test_records = [], [], []
for train_path, val_path, test_path in zip(train_paths, val_paths, test_paths):
    with open(train_path, 'r') as f:
        train_records.extend(json.load(f))
    with open(val_path, 'r') as f:
        val_records.extend(json.load(f))
    with open(test_path, 'r') as f:
        test_records.extend(json.load(f))

for record in train_records:
    aa = record['aa_seq']
    encoded = tokenizer.batch_encode_plus([record['smiles']])
    smiles = torch.tensor(encoded['input_ids'][0])
    if len(aa) > max_len[0]:
        max_len[0] = len(aa)
    if len(aa) < min_len[0]:
        min_len[0] = len(aa)
    if len(smiles) > max_len[1]:
        max_len[1] = len(smiles)
    if len(smiles) < min_len[1]:
        min_len[1] = len(smiles)

for record in val_records:
    aa = record['aa_seq']
    encoded = tokenizer.batch_encode_plus([record['smiles']])
    smiles = torch.tensor(encoded['input_ids'][0])
    if len(aa) > max_len[0]:
        max_len[0] = len(aa)
    if len(aa) < min_len[0]:
        min_len[0] = len(aa)
    if len(smiles) > max_len[1]:
        max_len[1] = len(smiles)
    if len(smiles) < min_len[1]:
        min_len[1] = len(smiles)

# for record in test_records:
#     smiles = record['smiles']
#     if len(smiles) > max_len[1]:
#         max_len[1] = len(smiles)
#     if len(smiles) < min_len[1]:
#         min_len[1] = len(smiles)

data = {
    "data_type": ["AA Seq", "SMILES"],
    "min_len": min_len,
    "max_len": max_len,
}

import pandas as pd
import utils as ut

df = pd.DataFrame(data)
df.to_csv(ut.abspath(f'out/metrics/statistic_on_seq_len.csv'), index=False, na_rep=0)

    