In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

import utils as ut

organism = 'others'

train_paths = [f'data/sp_data/train_set_partition_0_{organism}.json',
               f'data/sp_data/train_set_partition_1_{organism}.json']
val_paths = [f'data/sp_data/test_set_partition_0_{organism}.json',
             f'data/sp_data/test_set_partition_1_{organism}.json']
test_paths = [f'data/sp_data/train_set_partition_2_{organism}.json',
              f'data/sp_data/test_set_partition_2_{organism}.json']

train = pd.concat(pd.read_json(path) for path in ut.abspaths(train_paths))
val = pd.concat(pd.read_json(path) for path in ut.abspaths(val_paths))
test = pd.concat(pd.read_json(path) for path in ut.abspaths(test_paths))

keys = train['kingdom'].unique()
t = train['kingdom'].value_counts(sort=False).tolist()
# print(t.iloc[0])

plt.bar(keys, t, align='center')
xlocs, xlabs = plt.xticks()
for i, v in enumerate(t):
    plt.text(xlocs[i] - 0.1, v + 100, str(v))
plt.show()
# plt.savefig(fname=str(Path(params)))

In [ ]:
import torch

CKPT_PATH = './checkpoints/transformer_epoch=3_kaggle_v2.ckpt'

checkpoint = torch.load(CKPT_PATH)
print(checkpoint.keys())
print(checkpoint['state_dict'])

In [ ]:
import pandas as pd
import json

train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
val_paths = [f'data/sp_data/test_set_partition_0.json', f'data/sp_data/test_set_partition_1.json']
test_paths = [f'data/sp_data/train_set_partition_2.json', f'data/sp_data/test_set_partition_2.json']

train_data = []
val_data = []
test_data = []

for path in train_paths:
    with open(path, 'r') as f:
        data = json.load(f)
        train_data.extend(data)

train_data = pd.DataFrame(train_data)
train_data

In [ ]:
t = {
    "c": 4,
    "b": 2,
    "a": 3,
}

c = dict(a=1, b=2, c=3)

tt = dict(sorted(t.items(), key=lambda kv: c[kv[0]]))

In [ ]:
list(tt.keys())

In [1]:
len("MAPTLFQKLFSKRTGLGAPGRDARDPDCGFSWPLPEFDPSQIRLIVYQDCERRGRNVLFDSSVKRRNEDI")

70

In [7]:
import tokenizer.tokenizer_utils as tut
import torch
tokenizer = tut.load_tokenizer('cnn', 'smiles')
encoded = tokenizer.batch_encode_plus(["N[C@@H](CCSC)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCSC)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC1=CC=C(O)C=C1)C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)N[C@@H](CC1=CNC=N1)C(=O)N[C@@H](CC1=CNC=N1)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H](CCCNC(N)=N)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CCSC)C(=O)NCC(=O)N[C@@H](C)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](C)C(=O)N[C@@H](CS)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(N)=O)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CCC(N)=O)C(=O)N1[C@@H](CCC1)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCSC)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(C))C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CCSC)C(=O)N[C@@H](CCCNC(N)=N)C(=O)NCC(=O)NCC(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC1=CC=C(O)C=C1)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC(O)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(C))C(=O)O"])
print(torch.tensor(encoded['input_ids'][0]))

tensor([ 1, 13, 16, 11, 19, 12, 20, 38,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12,
        20, 33,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12, 20, 38,  6, 11, 21, 14,
         6, 13, 16, 11, 19, 12, 20, 33,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12,
        20, 25,  9, 18,  9, 11,  5, 14,  6, 11,  9, 27,  6, 11, 21, 14,  6, 13,
        16, 11, 19, 12, 20, 25,  9, 18,  9, 18,  9, 27,  6, 11, 21, 14,  6, 13,
        16, 11, 19, 12, 20, 25,  9, 36,  9, 29,  6, 11, 21, 14,  6, 13, 16, 11,
        19, 12, 20, 25,  9, 36,  9, 29,  6, 11, 21, 14,  6, 29, 16, 11, 19, 12,
        20, 35,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12, 20, 31,  6, 11, 21, 14,
         6, 28, 21, 14,  6, 13, 16, 11, 19, 12, 20, 18,  5, 11,  6, 11,  6, 11,
        21, 14,  6, 13, 16, 11, 19, 12, 20, 18,  5, 11,  6, 11,  6, 11, 21, 14,
         6, 29, 16, 11, 19, 12, 20, 35,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12,
        20, 34,  5, 13, 22, 13,  6, 11, 21, 14,  6, 13, 16, 11, 19, 12, 20, 18,
         5, 11,  6, 11,  6, 11, 21, 14, 

In [ ]:
import params

a = list(params.SP_LABELS.keys()).insert(0, 'metrics')
b = list(params.SP_LABELS.keys())
b.insert(0, 'metrics')
print(a)

In [ ]:
import torch

p = torch.tensor([[1, 2, 3],
                  [1, 2, 5],
                  [4, 1, 1],
                  [2, 3, 2],
                  [2, 4, 2]], dtype=torch.float)
t = torch.tensor([2, 1, 0, 1, 2])
t2 = torch.tensor([2, 2, 0, 1, 2])

from sklearn.metrics import f1_score, classification_report
import numpy as np

from torchmetrics import F1Score

f1 = F1Score(task='multiclass', num_classes=3, average=None)

print(f1(p, t2))
print(f1_score(torch.argmax(p, dim=1).tolist(), t2.tolist(), average=None, zero_division=np.nan))
print(classification_report(torch.argmax(p, dim=1).tolist(), t2.tolist()))



In [ ]:

import torch

cm = torch.tensor([
    [1, 2, 3],
    [2, 4, 5],
    [3, 1, 2],
])

tp = torch.diag(cm)
fp = torch.sum(cm, dim=0) - tp
fn = torch.sum(cm, dim=1) - tp
tn = torch.sum(cm) - (tp + fn + fp)

denom = (tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)
torch.sqrt(denom)
# math.sqrt(denom)

# print((tp * tn + fp * fn) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)))

In [ ]:
n = torch.tensor([1, 2])
d = torch.tensor([2, 0])

z = torch.tensor(2)
if z == 0:
    print('true')

for i, j in zip(n, d):
    if j == 0:
        print(0)
    else:
        print((i / j).item())

In [8]:
from data.sp_dataset import SPDataset
from data.data_utils import SPBatchRandomSampler
import utils as ut
from torch.utils.data import DataLoader

train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
train_set = SPDataset(json_paths=ut.abspaths(train_paths), data_type='aa')
# torch.manual_seed(0)
sampler = SPBatchRandomSampler(train_set, batch_size=2, current_epoch=0, shuffle=True)
train_dataloader = DataLoader(train_set, batch_sampler=sampler)
for idx, batch in enumerate(train_dataloader):
    pass
    # print(idx, batch)

In [5]:
import torch

train_paths = [f'data/sp_data/train_set_partition_0.json', f'data/sp_data/train_set_partition_1.json']
train_set = SPDataset(json_paths=ut.abspaths(train_paths), data_type='aa')
print(range(3))
subset = torch.utils.data.Subset(train_set, range(3))
print(len(subset))

In [5]:
a = ((1, 2, 3), 4, 5)
b = ((4, 2, 3), 5, 7)
c = ((4, 6, 2), 4, 1)
batch = [a, b, c]
x, y, z = map(list, zip(*batch))
print(x, y, z)

In [21]:
from dgl.nn.pytorch import GraphConv
import dgl
import torch

num_nodes = 10

a = [0, 1, 2, 3, 4, 3]
b = [1, 0, 3, 2, 3, 4]
a1 = torch.zeros((num_nodes, num_nodes))
for i, j in zip(a, b):
    a1[i, j] = 1
g1 = dgl.graph((a, b), num_nodes=num_nodes)
g1 = dgl.add_self_loop(g1)
g1.ndata['h'] = a1

c = [0, 1, 2, 3, 6, 3]
d = [1, 0, 3, 2, 3, 6]
a2 = torch.zeros((num_nodes, num_nodes))
for i, j in zip(c, d):
    a2[i, j] = 1
g2 = dgl.graph((c, d), num_nodes=num_nodes)
g2 = dgl.add_self_loop(g2)
g2.ndata['h'] = a2

batch = dgl.batch([g1, g2])
# feats = torch.concat([a1, a2])

conv = GraphConv(in_feats=num_nodes, out_feats=2, allow_zero_in_degree=True)
ret = conv(batch, batch.ndata['h'])
# ret = conv(g2, a2)
print(torch.reshape(ret, (-1, num_nodes, 2)).shape)

In [5]:
from dgl.data import MiniGCDataset
import matplotlib.pyplot as plt
import networkx as nx

# A dataset with 80 samples, each graph is
# of size [10, 20]
dataset = MiniGCDataset(80, 10, 20)
graph, label = dataset[0]
fig, ax = plt.subplots()
nx.draw(graph.to_networkx(), ax=ax)
ax.set_title('Class: {:d}'.format(label))
plt.show()

In [13]:
import torch

t1 = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [1, 2, 3],
        [0, 0, 0]
    ]
])

t2 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [1,2,3]
])

split_ids = torch.tensor([2, 1])

d_model = 3

from itertools import islice

def split_batch(batch, split_ids, max_len):
    tmp = iter(batch)
    res = [list(islice(tmp, 0, ele)) for ele in split_ids]
    print(res)
    ret = []
    if max_len == "longest":
        max_len = torch.max(split_ids)
        # print(max_len)
    # if not isinstance(max_len, int):
    #     raise ValueError('Use `int` or "longest"')
    for ele in res:
        print(ele)
        if len(ele) > max_len:
            ret.append(torch.stack(ele[:max_len]))
        else:
            while len(ele) < max_len:
                pad = torch.zeros(d_model)
                ele.append(pad)
            ret.append(torch.stack(ele))
    return torch.stack(ret)
print(split_batch(t2, split_ids, "longest"))

[[tensor([1, 2, 3]), tensor([4, 5, 6])], [tensor([1, 2, 3])]]
[tensor([1, 2, 3]), tensor([4, 5, 6])]
[tensor([1, 2, 3])]
tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [0., 0., 0.]]])


In [1]:
import torch

t = torch.tensor([
    [1., 1., 1.],
    [1., 0., 0.]
])

t = t.masked_fill(t == 0, float('-inf'))
print(t)
t = t.masked_fill(t == 1, float(0.0))
print(t)

tensor([[1., 1., 1.],
        [1., -inf, -inf]])
tensor([[0., 0., 0.],
        [0., -inf, -inf]])


In [11]:
t = torch.zeros((8, 4))
t[:, -1] = float('-inf')
print(t)

tensor([[0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., -inf]])


In [14]:
import torch
t1 = torch.tensor([0,0,0])
t2 = [
    torch.tensor([1,0,0]),
    torch.tensor([0,1,0]),
]
print(torch.stack([t1, *t2]))

tensor([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]])


In [15]:
t = [1,2,3]
t[len(t)]

IndexError: list index out of range